package com.jg.wx.dao;

import com.jg.wx.domain.JgBusOrder;
import org.apache.ibatis.annotations.Param;

public interface JgBusOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jg_hy_bus_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jg_hy_bus_order
     *
     * @mbg.generated
     */
    int insert(JgBusOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jg_hy_bus_order
     *
     * @mbg.generated
     */
    int insertSelective(JgBusOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jg_hy_bus_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    JgBusOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") JgBusOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jg_hy_bus_order
     *
     * @mbg.generated
     */
    JgBusOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jg_hy_bus_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JgBusOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jg_hy_bus_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JgBusOrder record);
}