package com.jg.wx.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class JgBusOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.home_address
     *
     * @mbg.generated
     */
    private String homeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.home_address_lng
     *
     * @mbg.generated
     */
    private String homeAddressLng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.home_address_lat
     *
     * @mbg.generated
     */
    private String homeAddressLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.corp_address
     *
     * @mbg.generated
     */
    private String corpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.corp_address_lng
     *
     * @mbg.generated
     */
    private String corpAddressLng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.corp_address_lat
     *
     * @mbg.generated
     */
    private String corpAddressLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.people_num
     *
     * @mbg.generated
     */
    private Integer peopleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.start_time
     *
     * @mbg.generated
     */
    private LocalDateTime startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.predict_fee
     *
     * @mbg.generated
     */
    private Double predictFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.contract_fee
     *
     * @mbg.generated
     */
    private Double contractFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.coupon_fee
     *
     * @mbg.generated
     */
    private Double couponFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jg_hy_bus_order.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.id
     *
     * @return the value of jg_hy_bus_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.id
     *
     * @param id the value for jg_hy_bus_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.order_id
     *
     * @return the value of jg_hy_bus_order.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.order_id
     *
     * @param orderId the value for jg_hy_bus_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.home_address
     *
     * @return the value of jg_hy_bus_order.home_address
     *
     * @mbg.generated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.home_address
     *
     * @param homeAddress the value for jg_hy_bus_order.home_address
     *
     * @mbg.generated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.home_address_lng
     *
     * @return the value of jg_hy_bus_order.home_address_lng
     *
     * @mbg.generated
     */
    public String getHomeAddressLng() {
        return homeAddressLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.home_address_lng
     *
     * @param homeAddressLng the value for jg_hy_bus_order.home_address_lng
     *
     * @mbg.generated
     */
    public void setHomeAddressLng(String homeAddressLng) {
        this.homeAddressLng = homeAddressLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.home_address_lat
     *
     * @return the value of jg_hy_bus_order.home_address_lat
     *
     * @mbg.generated
     */
    public String getHomeAddressLat() {
        return homeAddressLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.home_address_lat
     *
     * @param homeAddressLat the value for jg_hy_bus_order.home_address_lat
     *
     * @mbg.generated
     */
    public void setHomeAddressLat(String homeAddressLat) {
        this.homeAddressLat = homeAddressLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.corp_address
     *
     * @return the value of jg_hy_bus_order.corp_address
     *
     * @mbg.generated
     */
    public String getCorpAddress() {
        return corpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.corp_address
     *
     * @param corpAddress the value for jg_hy_bus_order.corp_address
     *
     * @mbg.generated
     */
    public void setCorpAddress(String corpAddress) {
        this.corpAddress = corpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.corp_address_lng
     *
     * @return the value of jg_hy_bus_order.corp_address_lng
     *
     * @mbg.generated
     */
    public String getCorpAddressLng() {
        return corpAddressLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.corp_address_lng
     *
     * @param corpAddressLng the value for jg_hy_bus_order.corp_address_lng
     *
     * @mbg.generated
     */
    public void setCorpAddressLng(String corpAddressLng) {
        this.corpAddressLng = corpAddressLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.corp_address_lat
     *
     * @return the value of jg_hy_bus_order.corp_address_lat
     *
     * @mbg.generated
     */
    public String getCorpAddressLat() {
        return corpAddressLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.corp_address_lat
     *
     * @param corpAddressLat the value for jg_hy_bus_order.corp_address_lat
     *
     * @mbg.generated
     */
    public void setCorpAddressLat(String corpAddressLat) {
        this.corpAddressLat = corpAddressLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.people_num
     *
     * @return the value of jg_hy_bus_order.people_num
     *
     * @mbg.generated
     */
    public Integer getPeopleNum() {
        return peopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.people_num
     *
     * @param peopleNum the value for jg_hy_bus_order.people_num
     *
     * @mbg.generated
     */
    public void setPeopleNum(Integer peopleNum) {
        this.peopleNum = peopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.start_time
     *
     * @return the value of jg_hy_bus_order.start_time
     *
     * @mbg.generated
     */
    public LocalDateTime getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.start_time
     *
     * @param startTime the value for jg_hy_bus_order.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.end_time
     *
     * @return the value of jg_hy_bus_order.end_time
     *
     * @mbg.generated
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.end_time
     *
     * @param endTime the value for jg_hy_bus_order.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.predict_fee
     *
     * @return the value of jg_hy_bus_order.predict_fee
     *
     * @mbg.generated
     */
    public Double getPredictFee() {
        return predictFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.predict_fee
     *
     * @param predictFee the value for jg_hy_bus_order.predict_fee
     *
     * @mbg.generated
     */
    public void setPredictFee(Double predictFee) {
        this.predictFee = predictFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.contract_fee
     *
     * @return the value of jg_hy_bus_order.contract_fee
     *
     * @mbg.generated
     */
    public Double getContractFee() {
        return contractFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.contract_fee
     *
     * @param contractFee the value for jg_hy_bus_order.contract_fee
     *
     * @mbg.generated
     */
    public void setContractFee(Double contractFee) {
        this.contractFee = contractFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.coupon_fee
     *
     * @return the value of jg_hy_bus_order.coupon_fee
     *
     * @mbg.generated
     */
    public Double getCouponFee() {
        return couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.coupon_fee
     *
     * @param couponFee the value for jg_hy_bus_order.coupon_fee
     *
     * @mbg.generated
     */
    public void setCouponFee(Double couponFee) {
        this.couponFee = couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jg_hy_bus_order.create_time
     *
     * @return the value of jg_hy_bus_order.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jg_hy_bus_order.create_time
     *
     * @param createTime the value for jg_hy_bus_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jg_hy_bus_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", homeAddress=").append(homeAddress);
        sb.append(", homeAddressLng=").append(homeAddressLng);
        sb.append(", homeAddressLat=").append(homeAddressLat);
        sb.append(", corpAddress=").append(corpAddress);
        sb.append(", corpAddressLng=").append(corpAddressLng);
        sb.append(", corpAddressLat=").append(corpAddressLat);
        sb.append(", peopleNum=").append(peopleNum);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", predictFee=").append(predictFee);
        sb.append(", contractFee=").append(contractFee);
        sb.append(", couponFee=").append(couponFee);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jg_hy_bus_order
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JgBusOrder other = (JgBusOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getHomeAddress() == null ? other.getHomeAddress() == null : this.getHomeAddress().equals(other.getHomeAddress()))
            && (this.getHomeAddressLng() == null ? other.getHomeAddressLng() == null : this.getHomeAddressLng().equals(other.getHomeAddressLng()))
            && (this.getHomeAddressLat() == null ? other.getHomeAddressLat() == null : this.getHomeAddressLat().equals(other.getHomeAddressLat()))
            && (this.getCorpAddress() == null ? other.getCorpAddress() == null : this.getCorpAddress().equals(other.getCorpAddress()))
            && (this.getCorpAddressLng() == null ? other.getCorpAddressLng() == null : this.getCorpAddressLng().equals(other.getCorpAddressLng()))
            && (this.getCorpAddressLat() == null ? other.getCorpAddressLat() == null : this.getCorpAddressLat().equals(other.getCorpAddressLat()))
            && (this.getPeopleNum() == null ? other.getPeopleNum() == null : this.getPeopleNum().equals(other.getPeopleNum()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getPredictFee() == null ? other.getPredictFee() == null : this.getPredictFee().equals(other.getPredictFee()))
            && (this.getContractFee() == null ? other.getContractFee() == null : this.getContractFee().equals(other.getContractFee()))
            && (this.getCouponFee() == null ? other.getCouponFee() == null : this.getCouponFee().equals(other.getCouponFee()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jg_hy_bus_order
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getHomeAddress() == null) ? 0 : getHomeAddress().hashCode());
        result = prime * result + ((getHomeAddressLng() == null) ? 0 : getHomeAddressLng().hashCode());
        result = prime * result + ((getHomeAddressLat() == null) ? 0 : getHomeAddressLat().hashCode());
        result = prime * result + ((getCorpAddress() == null) ? 0 : getCorpAddress().hashCode());
        result = prime * result + ((getCorpAddressLng() == null) ? 0 : getCorpAddressLng().hashCode());
        result = prime * result + ((getCorpAddressLat() == null) ? 0 : getCorpAddressLat().hashCode());
        result = prime * result + ((getPeopleNum() == null) ? 0 : getPeopleNum().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getPredictFee() == null) ? 0 : getPredictFee().hashCode());
        result = prime * result + ((getContractFee() == null) ? 0 : getContractFee().hashCode());
        result = prime * result + ((getCouponFee() == null) ? 0 : getCouponFee().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table jg_hy_bus_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        orderId("order_id", "orderId", "INTEGER", false),
        homeAddress("home_address", "homeAddress", "VARCHAR", false),
        homeAddressLng("home_address_lng", "homeAddressLng", "VARCHAR", false),
        homeAddressLat("home_address_lat", "homeAddressLat", "VARCHAR", false),
        corpAddress("corp_address", "corpAddress", "VARCHAR", false),
        corpAddressLng("corp_address_lng", "corpAddressLng", "VARCHAR", false),
        corpAddressLat("corp_address_lat", "corpAddressLat", "VARCHAR", false),
        peopleNum("people_num", "peopleNum", "INTEGER", false),
        startTime("start_time", "startTime", "TIMESTAMP", false),
        endTime("end_time", "endTime", "TIMESTAMP", false),
        predictFee("predict_fee", "predictFee", "DOUBLE", false),
        contractFee("contract_fee", "contractFee", "DOUBLE", false),
        couponFee("coupon_fee", "couponFee", "DOUBLE", false),
        createTime("create_time", "createTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jg_hy_bus_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}